feat: doubleTapGesture must depend on pinchEnabled
pavelbabenko/react-native-awesome-gallery pull request #54
Opened 2023-12-07 03:38 UTC by baronha

I think when `pinchEnable  === false` => `doubleTap` for zooming should also be disabled. Or is there an alternative prop to turn this off? 
In my case, there is an Video Item and I don't want the user to be able to zoom into my <VideoView />

2023-12-07 19:09 UTC, pavelbabenko commented
Hey @baronha
Good catch! But it's better to introduce new prop `doubleTapEnabled`
Will you be able to add it?

2023-12-08 09:57 UTC, pavelbabenko requested changes

2023-12-08 09:57 UTC, pavelbabenko commented on example/src/screens/Photos.tsx
> +        pinchEnabled={true}
This can be removed

2023-12-08 10:13 UTC, baronha commented on example/src/screens/Photos.tsx
> +        pinchEnabled={true}
I have removed that part

2023-12-09 11:35 UTC, merged

2023-12-09 11:41 UTC, pavelbabenko commented
@baronha released in https://github.com/pavelbabenko/react-native-awesome-gallery/releases/tag/v0.3.8